# Generated by Django 5.2 on 2025-04-10 21:38

import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0002_alter_call_med_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callquestion',
            name='questions',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='department', chained_model_field='department', to='med_app.question'),
        ),
    ]
