# Generated by Django 5.2 on 2025-04-12 19:33

import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0003_alter_callquestion_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callquestion',
            name='questions',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='department', chained_model_field='department', to='med_app.question'),
        ),
    ]
