# Generated by Django 5.2 on 2025-04-18 19:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0004_alter_callquestion_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время посещения')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина посещения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки оператора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации')),
                ('med_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='med_app.medcard', verbose_name='Медицинская карта пациента')),
                ('operator', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_visits', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ['-visit_time'],
            },
        ),
    ]
