# Generated by Django 5.2 on 2025-05-04 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0006_alter_call_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='recording',
        ),
    ]
