# Generated by Django 5.2 on 2025-05-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0007_remove_call_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='recording_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Путь к записи'),
        ),
    ]
