# Generated by Django 5.2 on 2025-05-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0008_call_recording_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='ip_operator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Оператор IP-телефонии'),
        ),
    ]
