# Generated by Django 5.2.4 on 2025-07-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0010_alter_call_options_alter_call_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medcard',
            name='phone_number',
            field=models.CharField(default=' ', max_length=11, verbose_name='phone number'),
        ),
    ]
