# Generated by Django 5.2.4 on 2025-07-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0011_medcard_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medcard',
            name='phone_number',
            field=models.CharField(default=' ', max_length=13, verbose_name='phone number'),
        ),
    ]
