# Generated by Django 4.2.23 on 2025-07-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_app', '0012_alter_medcard_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medcard',
            name='phone_number',
            field=models.CharField(default=' ', max_length=13, verbose_name='Телефон'),
        ),
    ]
